Karafecho patch 2
ExposuresProvider/icees-api-config pull request #110
Opened 2024-02-21 21:14 UTC by karafecho

Edited search terms; commented out EPR/PEGS variables; corrected one minor typo.

2024-02-21 21:48 UTC, hyi reviewed
@karafecho I left some comments on covid all features yaml file. Basically all those variables cannot be commented out since they do exist in covid patient data.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
These three variables exist in covid patient data, so commenting them out in all features yaml file for covid will break the icees-db code when creating a new covid sqlite database. I think we will have to keep them to make the all features yaml file compatible with the current covid data.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -      search_term: body mass index
Same problem here - BMI_CATEGORY exists in patient data, so cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -      search_term: chronological age
Same comment as above - these variables cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -      search_term: roadway exposure
Same here - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -      search_term: biological sex
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -      search_term: household income
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: integer
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: string
Same as above - they cannot be commented out here.

2024-02-21 21:48 UTC, hyi commented on config/ground-truth-yaml-files/all_features_version_10.1_no_visit_variant_covid.yml
> -    type: integer
Same as above - they cannot be commented out here.

2024-02-21 21:56 UTC, karafecho commented
But your slack message indicated that we don't include the final EPR/PEGS join step for the covid and pcd datasets?

2024-02-21 22:31 UTC, hyi commented
Yeah, that would work. I can just write a script to remove those commented-out variables from covid data. Then this PR looks OK to me, but I'll defer the final approval of this PR to Max.

2024-02-21 22:31 UTC, hyi approved these changes

2024-02-21 22:34 UTC, karafecho commented
The next time we rerun FHIR PIT, which should be relatively soon, given the code extensions to support new/updated exposures data, then I think we can just skip the final EPR/PEGS join.

2024-02-21 23:57 UTC, hyi commented
That's right, I don't have to remove these variables from current COVID data given that we are going to rerun FHIR PIT to generate new COVID data soon.

2024-02-22 00:51 UTC, maximusunc reviewed
In general, I think the way you commented out the search term is ok and my generation script will be fine, but I would have just commented out the whole name_lookup block.

2024-02-22 18:22 UTC, maximusunc requested changes
Sorry if I was unclear earlier. I think the whole `name_lookup` block should be commented out.

# name_lookup:
#  -limit: 1
#   search_term: salbutamol

2024-02-23 01:33 UTC, karafecho commented
No, I understood your suggestion; I just thought that it might be easier to comment out the `search_term` only, so that if I want to include a commented-out `search_term` for some future reason, then I'd only have to remove the # from the `search_term`, not the whole block.

That said, if it makes things cleaner to comment out the whole block, then I can do that.

FWIW, as much as I hate these YAML files, I have been feeling good about cleaning them up and aligning them with project goals, so if commenting out the whole block is best practice, then we should do that.

2024-02-23 20:52 UTC, maximusunc commented
Yeah, I think it's cleaner and clearer if the whole block is commented out. If you want, I can make that change and use some keyboard shortcuts to do it all at once.

2024-02-23 22:47 UTC, karafecho commented
Yes, please. If you know how to apply keyboard shortcuts to comment out the whole block all it once, then that would be great. I was using find-and-replace, but that isn't a very efficient approach.

2024-02-24 01:19 UTC, maximusunc approved these changes

2024-02-26 16:00 UTC, hyi approved these changes

2024-02-26 16:06 UTC, merged